### ISSUE TITLE
Endpoint for deleting files

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#100]
Create an endpoint for deleting files.  Doesn't have to be in the initial public release.  Params sent by frontend would look something like this:  

```
{
  Signature string len=130
  Address string len=40 (only exists if it's a new account)
  RequestObject {
    FileAddress ? (however files are located for storage/retrieval)
    Timestamp int
  }
}
```

**Comment by rfornea** [comment]
A quick note about the request params mentioned in this issue.  

`Signature` and `Address` are reference to some verification that cryptographic verification that Connor will be adding to storage-node, to make sure that the file is only deleted by the person who uploaded it.  So, although we can go ahead and let those be part of the request, the initial version of this endpoint may not use that verification.  

`FileAddress` should be (or at least contain) the object key for the file in AWS.

**Comment by pzhao5** [comment]
Why do you need to the timestamp?

**Comment by rfornea** [comment]
I'm gonna move this to "done" and make a new issue for unit tests for any files that don't have them.

**Comment by pzhao5** [comment]
Close this one for now since it is done
