### ISSUE TITLE
Make the AccountID be a hash of the public address instead of directly being the public address

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#130]
Modify `routes/verification_utils.go`'s returnAccountID method.  Instead of returning the public address without the 0x prefix, let's return a hash of the public address.  We can use the `utils.Hash()` method and then `hex.EncodeToString`.  We will also need to modify the `models/accounts.go` file to change the length restrictions for accountID from 40 back to 64, and fix a bunch of unit tests that will inevitably be broken.

**Comment by pzhao5** [comment]
This is done, right?

**Comment by rfornea** [comment]
@pzhao5 Will be done as of #140
