### ISSUE TITLE
[Need Tests]Integration changes:  Update the `/upload` endpoint again

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#131]
Change upload endpoint from this:  

```
{
  "address": "a 42-char eth address with 0x prefix",
  "signature": "a 130 character string created when you signed the request with your private key or account handle",
  "uploadFile": {
    "chunkData": "a binary string of the chunk data",
    "endIndex": 2,
    "fileHandle": "a deterministically created file handle",
    "partIndex": 1
  }
}
```

...to this:  

```
{
  "address": "a 42-char eth address with 0x prefix",
  "signature": "a 130 character string created when you signed the request with your private key or account handle",
  "requestBody": "the upload body stringified",
  "chunkData": "a literal array of bytes"
}
```
`chunkData` will no longer be a binary string but will instead be an array of bytes.  For an explanation of why the we need to send a stringified `requestBody`, see this issue:  https://github.com/opacity/storage-node/issues/121 .  The `requestBody`, when unmarshalled, should look like this, and we should validate that we can unmarshal it to this:  
```
type UploadFileObj struct {
	FileHandle string `form:"fileHandle" binding:"required,len=64" minLength:"64" maxLength:"64" example:"a deterministically created file handle"`
	PartIndex  int    `form:"partIndex" binding:"required,gte=1" example:"1"`
	EndIndex   int    `form:"endIndex" binding:"required,gtefield=PartIndex" example:"2"`
}
```

We will no longer need to call `handleFirstChunk` because there will be an `/init-upload` endpoint added which will create the `file` row in the SQL table and start the multi-part upload with S3.  

Instead of uploading files to `(s3Url)/fileHandle`, instead upload them to `(s3Url)/fileHandle/file`.  We will be uploading other things to `(s3Url)/fileHandle/metadata` and `(s3Url)/fileHandle/thumbnail` so this will make it easier on us in the future.

**Comment by rfornea** [comment]
The `requestBody` aspect of these changes will already be in place when this goes into master:  

https://github.com/opacity/storage-node/pull/134

**Comment by pzhao5** [comment]
Also update the impl to only handle the upload part for multipart upload

**Comment by pzhao5** [comment]
This is done, right?

**Comment by rfornea** [comment]
@pzhao5 Mostly but not quite.  We'll still need to modify the `chunkData` to be an array of bytes, and we need to separate out the `chunkData` from the request of the `requestBody`.

**Comment by rfornea** [comment]
And we may need to make some changes to be able to upload to (s3Url)/fileHandle/file. We will be uploading other things to (s3Url)/fileHandle/metadata so this will make it easier on us in the future.

**Comment by rfornea** [comment]
@funkydrummer Also nearly done. Still need to change `RequestBody` to be `form` instead of `json`, still need to modify the chunkData to be an array of bytes, and we need to separate out the chunkData from the request of the `requestBody`. And update tests.

**Comment by rfornea** [comment]
Needs updated tests but is otherwise done.
