### ISSUE TITLE
Integration changes:  Add /upload-status endpoint and remove some responsibilities from /upload endpoint

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#138]
-Remove call to `err := models.CompleteUploadsNewerThan(time.Now().Add(newerThanOffset))` from `jobs/fileCleaner.go`.  We can probably completely remove the `CompleteUploadsNewerThan` method.  The reason we are removing this part of the cron job is because it will not have access to the user's accountID (because files and accounts are disassociated from the backend's perspective) which means it cannot update the account's `StorageUsed`.  So it is inadequate for our purposes.  

-Remove `EndIndex` from the `UploadFileObj` as it will become redundant.  Remove the `FinishUpload()` and `UseStorageSpaceInByte()` calls in the upload handler.  The upload endpoint will no longer be responsible for finishing the upload or updating the account's `StorageUsed` 

-Add an `/upload-status` endpoint.  The frontend will poll this endpoint when it is finished uploading the chunks, but it will likely only need to poll it once or a few times.  The responsibilities of this endpoint:
--completed the multipart upload (`FinishUpload()`)
--update user's account's `StorageUsed` (`UseStorageSpaceInByte()`)

Request would look like:  

```
{
  "address": "a 42-char eth address with 0x prefix",
  "signature": "a 130 character string created when you signed the request with your private key or account handle",
  "requestBody": "the finish upload body stringified",
}
```

The `requestBody`, when unmarshalled, should look like this, and we should validate that we can unmarshal it to this:  
```
type UploadStatusObj struct {
	FileHandle string `form:"fileHandle" binding:"required,len=64" minLength:"64" maxLength:"64" example:"a deterministically created file handle"`
}

```

The reason for this change is because checking if the upload is complete in the `/upload` endpoint could cause problems, because that check only occurs once and it's possible the `completedIndexes` aren't updated at that point, so we would miss our one chance to call S3 methods to complete the multipart upload.  Also the recurring call in `fileCleaner` doesn't meet our needs because that job will not have access to the account to be able to update the `StorageUsed`.  So adding an `/upload-status` endpoint that the frontend can poll solves our problems:  (1) the backend still has access to the account (it will determine this from the signature) to change the `StorageUsed` and (2) it won't matter if the upload isn't done the first time the check occurs in `FinishUpload()` because we will just check again on the next poll.

**Comment by rfornea** [comment]
@pzhao5  Here is another one that can be worked on.

**Comment by rfornea** [comment]
@funkydrummer  I believe we need this for the production release but we may be able to do without it for beta, if the frontend isn't ready to use this endpoint. We can leave the /upload endpoint responsible for completing the multipart upload and there's some hacky-but-quick changes we could make to /upload to alleviate the problems described in this issue.

**Comment by rfornea** [comment]
This issue is partially done. The responsibilities have not been removed from /upload and we don't have unit tests for this yet.

**Comment by rfornea** [comment]
Putting this back in icebox for now since it's not essential to beta.

**Comment by rfornea** [comment]
Turns out we needed this for beta after all.  The endpoint exists already, but still needs unit tests, and still needs changes to be made to /upload endpoint.

**Comment by pzhao5** [comment]
What are the change besides the tests?

**Comment by rfornea** [comment]
@pzhao5   Just this I think:  

```
-Remove EndIndex from the UploadFileObj as it will become redundant. Remove the FinishUpload() and UseStorageSpaceInByte() calls in the upload handler. The upload endpoint will no longer be responsible for finishing the upload or updating the account's StorageUsed
```
