### ISSUE TITLE
Regional filtering

### ISSUE THREAD

**Issue by funkydrummer** [opacity/storage-node#168]

**Comment by funkydrummer** [comment]
https://aws.amazon.com/blogs/security/how-to-use-aws-waf-to-filter-incoming-traffic-from-embargoed-countries/

**Comment by funkydrummer** [comment]
https://www.treasury.gov/about/organizational-structure/offices/pages/office-of-foreign-assets-control.aspx

**Comment by funkydrummer** [comment]
https://docs.aws.amazon.com/waf/latest/developerguide/web-acl-geo-conditions.html

https://www.countryipblocks.net/ofac.php

https://www.countryipblocks.net/blog/tag/ofac/

https://aws.amazon.com/firewall-manager/resources/

**Comment by rfornea** [comment]
This is done.  Currently blocking North Korea, Cuba, Syria, Iran, and Venezuela.  If we want to add more we have to update the "Blocked Countries" WAF in AWS.
