### ISSUE TITLE
Business Reports

### ISSUE THREAD

**Issue by funkydrummer** [opacity/storage-node#177]

**Comment by funkydrummer** [comment]
See Slack backends

**Comment by rfornea** [comment]
This is where the discussion starts:
https://opacitystorage.slack.com/archives/C8S052KDL/p1558801070001900

**Comment by rfornea** [comment]
There's two ways we can get the total size of all data stored and the total number of completed files.  We can check the SQL completed_files table, or we can check S3.  

Checking SQL is easy.  But it would be useful for us to check S3 also to see if there are any discrepancies.  Currently if there's 1000 files in the completed_files table, there should ideally be 2000 objects in the S3 bucket (1 for the file and 1 for the metadata).  

Checking S3 is a little more difficult.  The S3 API for golang doesn't seem to come with methods to count the total number of objects in a bucket or get the total size of data in a bucket unless I have missed something really obvious.  I guess we could call ListObjects and page through all the results and literally count them and add up the file size of each, but it seems like there should be a better way.    

Another option is to pull in the cloudwatch library and use this method:  

https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.GetMetricStatistics

^ But I am not sure if this is an additional service we'd have to pay for.  For now I'm just going to only use the metrics from SQL and we can decide what we want to do about the S3 metrics.
