### ISSUE TITLE
Separate KV database from the rest of the application

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#183]
We should separate the K:V database from the rest of the storage-node application, so that if the storage-node application crashes, the badger database doesn't crash with it.  Crashes can cause the badger database to become corrupted.  

Ideally this change wouldn't affect tons of code.  Maybe just some lines in kv_store.go to connect to the badger database which would now be living outside the application.

**Comment by pzhao5** [comment]
Sound like you want to make KV database as its own service that it would
connect to! Which required to implement http method. We could deploy them
both on the same host to improve performance.

**Comment by rfornea** [comment]
@pzhao5 Yeah sounds good to me.  I think it makes sense for it to still be on the same instance.

**Comment by pzhao5** [comment]
I can see that badger is very fast if you do so in the same process. Without jumping into another middle layer to access data.
In term of "Crashes can cause the badger database to become corrupted", where do you see that?? If so, we should file a bug to that project so that they can fix it upstream.

**Comment by rfornea** [comment]
> In term of "Crashes can cause the badger database to become corrupted", where do you see that??   

It was something that happened a few times back in the Oyster days, and it seemed to always happen when crashes occurred.

**Comment by pzhao5** [comment]
Do we still decide to go with this?

**Comment by rfornea** [comment]
I'm not sure, let's revisit later.  Either way it's not a priority right now.

**Comment by rfornea** [comment]
Let's just not worry about this.  The way I'm deploying now is different than how I used to do it and we aren't getting corruptions anymore as far as I can tell.
