### ISSUE TITLE
CheckIfPaid fails when user sends too much OPQ

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#194]
Staff did tests of 2.0, 2.1, and 2.34 OPQ payments and all of them work.  A user sent 17.977 OPQ and it did not work.  Staff tested with 17.976 and it also did not work.  

Somewhere between 2.34 and 17.976 there is a problem with the payment checking.

**Comment by rfornea** [comment]
While fixing this issue, we should also make a change to only collect 2.0 from the payment address, i.e. if the user send 2.34 OPQ, take only 2.0 and leave the .34.

**Comment by rfornea** [comment]
Disregard that last comment.  The user is responsible for not sending too much.

**Comment by tomwalsh96** [comment]
Shouldn't additional OPQ sent just extend the time data is persisted?

**Comment by MrRedPandabaer** [comment]
@tomwalsh96 The user is asked to only send a specific amount very clearly, not more. Additional OPQ does not extend the storage account time. The selected plan is 128gb for one year.
