### ISSUE TITLE
Track stripe metrics

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#252]
-add a `PaidWithCreditCard` boolean to `accounts` table.  We would set this to `true` in the `CheckChargePaid` method in the `stripe_payments` model, and we'll use this value when we're setting our stripe metrics.  

-add some metrics to `utils/metrics.go` for stripe payments.  We currently track total number of paid accounts, total number of paid accounts by account type (basic, professional, etc.).  We want to add additional metrics to further break this down based on whether an account was paid for with OPQ or with stripe.  Keep the current metrics and just add new ones.  We also currently the total percent of space used, and the percent of space used by account type (basic, professional, etc.).  Add additional metrics to further break this down based on whether the account was paid with stripe or with OPQ.  

-modify `jobs/metrics_collector.go` to set the additional metrics.

**Comment by rfornea** [comment]
This is done now right?

**Comment by pzhao5** [comment]
Right
