### ISSUE TITLE
Reporting: Space usage vs paid, key metric to know utilization rates

### ISSUE THREAD

**Issue by funkydrummer** [opacity/storage-node#48]
As a manager, I need to know space used vs space paid for in order to track utilization rates and potential storage capacity required to meet demand.

ie: Users will pay for 100gb, but maybe only use 50%? 

Solution:
Run a job that trolls through the Account table and tallies up all the StorageLimit values versus StorageUsed values. Could run every 24 hours or x.

**Comment by rfornea** [comment]
This is now a metric that prometheus knows about
