### ISSUE TITLE
Add metrics to prometheus for number of unique accounts

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#89]
Run a job every X minutes to count the number of unique accounts and set a metric on prometheus. 

![image](https://user-images.githubusercontent.com/17357002/55836801-8ebcd600-5aed-11e9-85a8-7ed909210ea0.png)

**Comment by funkydrummer** [comment]
Same as for files: the way I would do this for the website counter is increment a simple counter each time a payment is complete (account created), not worry about exact current amount. For internal metrics, we would eventually need total number currently active to remove expired accounts from total (not urgent for 1.0 release).

**Comment by pzhao5** [comment]
@funkydrummer, @rfornea does this metric need to be real time (same for number of file uploaded). Can it have some delay on the counter?

**Comment by rfornea** [comment]
@pzhao It sounds like Jason is wanting it to be real-time, i.e. it's probably more important for people to see the counter increment when they create an account and pay for it, than it is for it to be completely accurate.  

If we're going with an approach where the counter increments everytime the backend detects a new paid account, and if we're reportingsimilar data for files, maybe we should add a simple `metrics` table that stores such values so that they persist.

**Comment by pzhao5** [comment]
Make sense. How do you query this metric from the client. Does the client ping the Prometheus server every sec?

**Comment by pzhao5** [comment]
Or do we have an endpoint to return such info

**Comment by funkydrummer** [comment]
I don't think it has to be a 'real-time' counter. Some delay is fine.

**Comment by rfornea** [comment]
@pzhao5   We have the metrics endpoint that the client could query, or there may be some other way for the client to ask the instance's prometheus service directly (port 9100 or 9090 or something).

**Comment by pzhao5** [comment]
Should be query via /admin/user_stats endpoint
