### ISSUE TITLE
Add metrics to prometheus for number of files uploaded

### ISSUE THREAD

**Issue by rfornea** [opacity/storage-node#90]
Related to issue #89, we'll need to also add a metric for the total number of files uploaded.  But this one will be a bit more complicated because we can't just count the number of unique file rows in the database, as we may be deleting each row after an upload is finished.  

We could just count the total number of objects in the S3 bucket, if @funkydrummer is okay with this number meaning "total number of files that we are currently storing" and not "total number of files that we have ever stored" although it will be a long time before there's a discrepancy between these numbers.  Over time, objects will expire and be removed from S3.  We'll need to track this some other way if we want this number to represent total number of files that we have ever stored.  

![image](https://user-images.githubusercontent.com/17357002/55836801-8ebcd600-5aed-11e9-85a8-7ed909210ea0.png)

**Comment by funkydrummer** [comment]
The way I would do this for the website counter is increment a simple counter each time the full mutlipart upload is complete, not worry about exact current amount. For internal metrics, we could use total number of objects in S3 for total currently stored (not urgent for 1.0 release).
