### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by funkydrummer** [opacity/storage-node#99]
Upload threshold testing. 10, 100, 1000, 10000, etc files

**Comment by pzhao5** [comment]
Can you explain a bit more about this? What does 10, 100, 1000 files? Does size matter?

**Comment by funkydrummer** [comment]
@pzhao5 examples of increasing # of concurrent files to test in upload.

**Comment by rfornea** [comment]
I checked in some preliminary performance testing, that we can build upon later.  It just lives under storage_node/performance_test.go, and currently the tests are all skipped, but we can remove the t.skip() calls.
